# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dm-is-temporal}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joe Kutner"]
  s.date = %q{2011-03-08}
  s.description = %q{DataMapper plugin implementing temporal patterns}
  s.email = %q{jpkutner [a] gmail [d] com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/dm-is-temporal.rb",
    "lib/dm-is-temporal/is/temporal.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/temporal_spec.rb"
  ]
  s.homepage = %q{http://github.com/jkutner/dm-is-temporal}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{DataMapper plugin implementing temporal patterns}
  s.test_files = [
    "spec/spec_helper.rb",
    "spec/temporal_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

